[package]
name = "gitoxide"
description = "A command-line application for interacting with git repositories"
repository = "https://github.com/Byron/git-oxide"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
version = "0.3.0"
default-run = "gix"
include = ["src/**/*", "LICENSE-*", "README.md", "CHANGELOG.md"]

[[bin]]
name = "gix"
path = "src/porcelain-cli.rs"
test = false
doctest = false


[[bin]]
name = "gixp"
path = "src/plumbing-cli.rs"
test = false
doctest = false

[features]
default = ["max"]

max = ["fast", "pretty-cli", "prodash/render-tui-crossterm", "prodash-render-line-crossterm"]
max-termion = ["fast", "pretty-cli", "prodash/render-tui-termion", "prodash-render-line-termion"]

lean = ["fast", "lean-cli", "prodash-render-line-crossterm", "git-features/interrupt-handler", "prodash/progress-tree"]
lean-termion = ["fast", "lean-cli", "prodash-render-line-termion", "git-features/interrupt-handler", "prodash/progress-tree"]

light = ["fast", "lean-cli", "git-features/interrupt-handler"]
small = ["lean-cli"]

fast = ["git-features/parallel", "git-features/fast-sha1"]
pretty-cli = ["clap",
    "git-features/interrupt-handler",
    "gitoxide-core/serde1",
    "prodash/progress-tree",
    "prodash/progress-tree-log",
    "prodash/localtime",
    "prodash-render-tui",
    "prodash-render-line",
    "env_logger",
    "futures-lite"]
lean-cli = ["argh", "prodash/progress-log", "env_logger"]

prodash-render-line-crossterm = ["prodash-render-line", "prodash/render-line-crossterm", "atty", "crosstermion"]
prodash-render-line-termion = ["prodash-render-line", "prodash/render-line-termion", "atty", "crosstermion"]

# internal
prodash-render-tui = ["prodash/render-tui"]
prodash-render-line = ["prodash/render-line"]


[dependencies]
anyhow = "1.0.31"

gitoxide-core = { version = "0.3.0", path = "gitoxide-core" }
git-features = { version = "^0.3.0", path = "git-features" }

clap = { version = "3.0.0-beta.1", optional = true }
argh = { version = "0.1.3", optional = true, default-features = false }
prodash = { version = "8.0.0", optional = true, default-features = false }
atty = { version = "0.2.14", optional = true, default-features = false }
env_logger = { version = "0.7.1", optional = true, default-features = false, features = ["humantime", "termcolor", "atty"] }
crosstermion = { version = "0.3.0", optional = true, default-features = false }
futures-lite = { version = "0.1.10", optional = true, default-features = false }

[profile.release]
overflow-checks = false
lto = "fat"
panic = 'abort'
codegen-units = 1
incremental = false
build-override = { opt-level = 0 }

[workspace]
members = [
    "gitoxide-core",
    "git-features",
    "git-object",
    "git-ref",
    "git-odb",
    "git-repository",
    "git-protocol",
    "git-url",
    "git-transport",
    "git-tui",
]
