[package]
name = "gitoxide"
description = "A command-line application for interacting with git repositories"
repository = "https://github.com/Byron/gitoxide"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
version = "0.7.0"
default-run = "gix"
include = ["src/**/*", "LICENSE-*", "README.md", "CHANGELOG.md"]

[[bin]]
name = "gix"
path = "src/porcelain-cli.rs"
test = false
doctest = false


[[bin]]
name = "gixp"
path = "src/plumbing-cli.rs"
test = false
doctest = false

[features]
default = ["max"]

max = ["fast", "pretty-cli", "prodash/render-tui-crossterm", "prodash-render-line-crossterm", "prodash/render-line-autoconfigure", "http-client-curl", "gitoxide-core-tools", "gitoxide-core-blocking-client"]
max-termion = ["fast", "pretty-cli", "prodash/render-tui-termion", "prodash-render-line-termion", "prodash/render-line-autoconfigure", "http-client-curl", "gitoxide-core-tools", "gitoxide-core-blocking-client"]

lean = ["fast", "lean-cli", "prodash-render-line-crossterm", "git-features/interrupt-handler", "prodash/progress-tree", "http-client-curl", "gitoxide-core-tools", "gitoxide-core-blocking-client"]
lean-termion = ["fast", "lean-cli", "prodash-render-line-termion", "git-features/interrupt-handler", "prodash/progress-tree", "http-client-curl", "gitoxide-core-tools", "gitoxide-core-blocking-client"]

light = ["fast", "lean-cli", "git-features/interrupt-handler", "gitoxide-core-tools", "gitoxide-core-blocking-client"]
light-async = ["fast", "lean-cli", "git-features/interrupt-handler", "gitoxide-core-tools", "gitoxide-core-async-client"]
small = ["lean-cli", "git-features/sha1", "git-features/zlib-rust-backend"]

gitoxide-core-tools = ["gitoxide-core/organize", "gitoxide-core/estimate-hours"]
gitoxide-core-blocking-client = ["gitoxide-core/blocking-client"]
gitoxide-core-async-client = ["gitoxide-core/async-client", "futures-lite"]
http-client-curl = ["git-transport/http-client-curl"]
fast = ["git-features/parallel", "git-features/fast-sha1", "git-features/zlib-ng-compat"]

pretty-cli = ["clap",
    "git-features/interrupt-handler",
    "gitoxide-core/serde1",
    "prodash/progress-tree",
    "prodash/progress-tree-log",
    "prodash/localtime",
    "prodash-render-tui",
    "prodash-render-line",
    "env_logger",
    "futures-lite"]
lean-cli = ["argh", "prodash/progress-log", "env_logger"]

prodash-render-line-crossterm = ["prodash-render-line", "prodash/render-line-crossterm", "atty", "crosstermion"]
prodash-render-line-termion = ["prodash-render-line", "prodash/render-line-termion", "atty", "crosstermion"]

# internal
prodash-render-tui = ["prodash/render-tui"]
prodash-render-line = ["prodash/render-line"]

[dependencies]
anyhow = "1.0.41"

gitoxide-core = { version = "^0.9.0", path = "gitoxide-core" }
git-features = { version = "^0.15.0", path = "git-features" }
# just for feature configuration
git-transport = { optional = true, version = "^0.9.0", path = "git-transport" }

clap = { version = "=3.0.0-beta.2", optional = true }
argh = { version = "0.1.3", optional = true, default-features = false }
prodash = { version = "13.0.0", optional = true, default-features = false }
atty = { version = "0.2.14", optional = true, default-features = false }
env_logger = { version = "0.8.0", optional = true, default-features = false, features = ["humantime", "termcolor", "atty"] }
crosstermion = { version = "0.7.0", optional = true, default-features = false }
futures-lite = { version = "1.12.0", optional = true, default-features = false, features = ["std"] }

[profile.release]
overflow-checks = false
lto = "fat"
panic = 'abort'
codegen-units = 1
incremental = false
build-override = { opt-level = 0 }

# It's not quite worth building depencies with more optimizations yet. Let's keep it here for later.
#[profile.dev.package."*"]
#opt-level = 2

[workspace]
members = [
    "git-url",
    "git-hash",
    "git-validate",
    "git-ref",
    "git-config",
    "git-features",
    "git-commitgraph",
    "git-object",
    "git-diff",
    "git-traverse",
    "git-index",
    "git-packetline",
    "git-transport",
    "git-protocol",
    "git-pack",
    "git-odb",
    "git-repository",
    "gitoxide-core",
    "git-tui",

    "experiments/object-access",
    "experiments/diffing",
    "experiments/traversal",
    "experiments/hash-owned-borrowed",

    "tests/tools",
    "etc/utils"
]
