[package]
name = "git-config"
version = "0.1.0"
authors = ["Edward Shen <code@eddie.sh>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
serde = ["serde_crate"]

[dependencies]
bstr = "0.2.15"
nom = { version = "6", default_features = false, features = ["std"] }
serde_crate = { version = "1", package = "serde", optional = true}

[dev-dependencies]
serde_derive = "1.0"

[profile.release]
lto = true
codegen-units = 1