[package]
name = "git-config"
version = "0.1.0"
authors = ["Edward Shen <code@eddie.sh>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "6"
bstr = "0.2.15"

[dependencies.serde_crate]
package = "serde"
optional = true
version = " 1"

[dev-dependencies]
serde_derive = "1.0"

[features]
serde = ["serde_crate"]
