[package]
name = "git-features"
description = "A crate to integrate various capabilities using compile-time feature flags"
repository = "https://github.com/Byron/gitoxide"
version = "0.15.0"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
license = "MIT/Apache-2.0"
edition = "2018"

[lib]
doctest = false
test = false

[features]
progress = ["prodash"]
parallel = ["crossbeam-utils", "crossbeam-channel", "num_cpus", "jwalk"]
fast-sha1 = ["fastsha1"]
interrupt-handler = ["ctrlc"]
disable-interrupts = []
io-pipe = ["bytes"]
crc32 = ["crc32fast"]
zlib = ["flate2", "flate2/rust_backend", "quick-error"]
zlib-ng-compat = ["flate2/zlib-ng-compat"]
zlib-rust-backend = ["flate2/rust_backend"]

[[test]]
name = "hash"
path = "tests/hash.rs"
required-features = ["sha1"]

[[test]]
name = "parallel"
path = "tests/parallel_threaded.rs"
required-features = ["parallel", "sha1"]

[[test]]
name = "multi-threaded"
path = "tests/parallel_shared_threaded.rs"
required-features = ["parallel", "sha1"]

[[test]]
name = "single-threaded"
path = "tests/parallel_shared.rs"
required-features = ["sha1"]

[[test]]
name = "pipe"
path = "tests/pipe.rs"
required-features = ["io-pipe"]

[dependencies]
git-hash = { version = "^0.4.0", path = "../git-hash" }

# 'parallel' feature
crossbeam-utils = { version = "0.8.5", optional = true }
crossbeam-channel = { version = "0.5.0", optional = true }
num_cpus = { version = "1.13.0", optional = true }

jwalk = { version = "0.6.0", optional = true }
walkdir = { version = "2.3.1", optional = true } # used when parallel is off

# hashing and 'fast-sha1' feature
sha1 = { version = "0.6.0", optional = true }
crc32fast = { version = "1.2.1", optional = true }
fastsha1 = { package = "sha-1", version = "0.9.1", optional = true }

# progress
prodash = { version = "13.0.0", optional = true, default-features = false, features = ["unit-bytes", "unit-human"] }

# interrupt-handler
ctrlc = { version = "3.1.4", optional = true, default-features = false, features = ['termination'] }

# pipe
bytes = { version = "1.0.0", optional = true }

# zlib module
flate2 = { version = "1.0.17", optional = true, default-features = false }
quick-error = { version = "2.0.0", optional = true }

[package.metadata.docs.rs]
all-features = true

